### ISSUE TITLE
Problem with Running the Workflow in Galaxy Project

### ISSUE THREAD

**Issue by ox852** [kpbioteam/ewas_galaxy#7]
I was trying to 'Run' the workflow after uploading from https://training.galaxyproject.org/training-material/topics/epigenetics/tutorials/ewas-suite/workflows/ewas_training.ga, however, there is no such option in the galaxy interface to run it.

When 'Viewing' from the galaxy interface, there are warning messages of 'unknown tool with ids' from step 5 to 17 (except for 13 & 15).

Could I please know how can I solve this problem?

Thank you so much in advance.

**Comment by kpbioteam** [comment]
Hi ox852, 

Tools included in workflow have been updated and wrapped up as one single integrated tool called: "Infinium Human Methylation BeadChip " to perform your analysis please follow the tutorial available [here](https://training.galaxyproject.org/training-material/topics/epigenetics/tutorials/ewas-suite/tutorial.html). 
Apologise for the inconvenience. We will put additional effort to make sure outdated information is removed: [pull request](https://github.com/galaxyproject/training-material/pull/1918).
There is also publication available on following topic and can be found [here](https://academic.oup.com/gigascience/article/9/5/giaa049/5836679).

If we can be of assistance, please do not hesitate to contact us.
